name: API Tests

on:
  push:
    branches:
      - 'main'

jobs:
  deploy-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: setup.py

      - run: |
          python -m pip install -U pip setuptools wheel
          pip install pytest requests

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Wait for Cloud Run deployment
        run: |
          while true; do
            status=$(gcloud run services describe mlops-catsvsdogs --region us-central1 --format="value(status)")
            echo "Cloud Run service status: $status"
            if echo "$status" | grep -q "Ready"; then
              echo "Cloud Run service is Ready"
              break
            fi
            sleep 30
          done

      - name: Get Deployed Model URL
        id: get-url
        run: |
          PROJECT_ID="dtumlops-448016"
          SERVICE_NAME="mlops-catsvsdogs"
          REGION="us-central1"
          URL=$(gcloud run services describe $SERVICE_NAME --region=$REGION --format="value(status.url)")
          echo "DEPLOYED_MODEL_URL=$URL" >> $GITHUB_OUTPUT

      - name: Setup test files
        run: |
          mkdir -p tests/integration_tests
          curl https://placekitten.com/224/224 -o tests/integration_tests/cat.jpg

      - name: Run tests
        env:
          DEPLOYED_MODEL_URL: ${{ steps.get-url.outputs.DEPLOYED_MODEL_URL }}
        run: |
          pytest tests/integration_tests/test_apis.py -v --junitxml=test-results.xml

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results.xml
