name: API Test

on:
  push:
    branches:
      - 'main'

jobs:
  api-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt

      - name: Run API tests
        env:
          DEPLOYED_MODEL_URL: "https://mlops-catsvsdogs-122709719634.us-central1.run.app"
        run: |
          pytest tests/integration_tests/test_apis.py --maxfail=1 --disable-warnings -v
