name: Locust Load Test

on:
  push:
    branches:
      - 'main'

jobs:
  deploy-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: setup.py
      - run: |
          python -m pip install -U pip setuptools wheel
          pip install locust

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Wait for Cloud Run deployment
        run: |
          while true; do
            status=$(gcloud run services describe mlops-catsvsdogs --region us-central1 --format="value(status)")
            echo "Cloud Run service status: $status"
            if echo "$status" | grep -q "Ready"; then
              echo "Cloud Run service is Ready"
              break
            fi
            sleep 30
          done

      - name: Get Deployed Model URL
        id: get-url
        run: |
          PROJECT_ID="dtumlops-448016"
          SERVICE_NAME="mlops-catsvsdogs"
          REGION="us-central1"
          URL=$(gcloud run services describe $SERVICE_NAME --region=$REGION --format="value(status.url)")
          echo "DEPLOYED_MODEL_URL=$URL" >> $GITHUB_OUTPUT

      - name: Run load test
        env:
          DEPLOYED_MODEL_URL: ${{ steps.get-url.outputs.DEPLOYED_MODEL_URL }}
          LOCUST_USERS: "50"
          LOCUST_RATE: "10"
          LOCUST_RUNTIME: "1m"
        run: |
          locust -f tests/performance_test/locust.py \
            --headless -u ${{ env.LOCUST_USERS }} -r ${{ env.LOCUST_RATE }} --run-time ${{ env.LOCUST_RUNTIME }} --host=${{ env.DEPLOYED_MODEL_URL }} --csv=locust/locust

      - name: Upload locust results
        uses: actions/upload-artifact@v4
        with:
          name: locust-results
          path: locust/locust*.csv
